// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG9XGO1FNsX9RMfhT6x_C9JskSmxaaI9o',
    appId: '1:392763151438:web:2a84c3c0e6e088cd225f1f',
    messagingSenderId: '392763151438',
    projectId: 'catalyst-fcm',
    authDomain: 'catalyst-fcm.firebaseapp.com',
    storageBucket: 'catalyst-fcm.firebasestorage.app',
    measurementId: 'G-W3DZ9BC4R0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJjyEwTZq9VSM9CZ_hih9vzxO5XNH9NO4',
    appId: '1:392763151438:android:acd59943ae53f297225f1f',
    messagingSenderId: '392763151438',
    projectId: 'catalyst-fcm',
    storageBucket: 'catalyst-fcm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkvdsBTRUctBBVDN3YfK5-GKSzk0KapwA',
    appId: '1:392763151438:ios:32400a85c7cec603225f1f',
    messagingSenderId: '392763151438',
    projectId: 'catalyst-fcm',
    storageBucket: 'catalyst-fcm.firebasestorage.app',
    iosBundleId: 'com.example.catalystStudent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkvdsBTRUctBBVDN3YfK5-GKSzk0KapwA',
    appId: '1:392763151438:ios:32400a85c7cec603225f1f',
    messagingSenderId: '392763151438',
    projectId: 'catalyst-fcm',
    storageBucket: 'catalyst-fcm.firebasestorage.app',
    iosBundleId: 'com.example.catalystStudent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCG9XGO1FNsX9RMfhT6x_C9JskSmxaaI9o',
    appId: '1:392763151438:web:38d193a76151caf8225f1f',
    messagingSenderId: '392763151438',
    projectId: 'catalyst-fcm',
    authDomain: 'catalyst-fcm.firebaseapp.com',
    storageBucket: 'catalyst-fcm.firebasestorage.app',
    measurementId: 'G-QK90T9RSEK',
  );
}
